import { useEffect, useState } from 'react';
import { AVATARS } from '../components/OnboardingWizard';
import { createHouseholdInvite, getActiveHouseholdInvite, revokeHouseholdInvite } from '../services/householdInvitesService';

function SettingsFamilyPage({ household, users, accessMembers = [], membershipRole, onBack, onUpdateHouseholdName, onCreateUser, onUpdateUser, onDeleteUser, onStatus }) {
  const [editingFamily, setEditingFamily] = useState(false);
  const [familyName, setFamilyName] = useState(household?.name || '');
  const [draft, setDraft] = useState(null);
  const [saving, setSaving] = useState(false);
  const [invite, setInvite] = useState(null);
  const [inviteLoading, setInviteLoading] = useState(false);
  const [inviteLoaded, setInviteLoaded] = useState(false);
  const saveFamily = async () => { if (!familyName.trim()) return; setSaving(true); try { await onUpdateHouseholdName(familyName.trim()); setEditingFamily(false); onStatus('Название семьи сохранено'); } catch { onStatus('Не удалось сохранить название семьи'); } finally { setSaving(false); } };
  const saveUser = async () => { if (!draft?.name?.trim()) return; setSaving(true); try { if (draft.id) await onUpdateUser(draft.id, draft); else await onCreateUser(draft); setDraft(null); onStatus('Участник сохранён'); } catch { onStatus('Не удалось сохранить участника'); } finally { setSaving(false); } };
  const loadInvite = async () => { setInviteLoading(true); try { setInvite(await getActiveHouseholdInvite()); } catch (error) { console.error(error); onStatus('Не удалось загрузить приглашение'); } finally { setInviteLoaded(true); setInviteLoading(false); } };
  const createInvite = async () => { setInviteLoading(true); try { const next = await createHouseholdInvite(); setInvite(next); onStatus('Приглашение создано'); } catch (error) { console.error(error); const reason = String(error?.message || '').replace(/^household_invites\.create_household_invite:\s*/i, ''); onStatus(reason ? `Не удалось создать приглашение: ${reason}` : 'Не удалось создать приглашение'); } finally { setInviteLoaded(true); setInviteLoading(false); } };
  const copyInvite = async () => { try { await navigator.clipboard.writeText(invite?.code || ''); onStatus('Код скопирован'); } catch { onStatus('Не удалось скопировать код'); } };
  const owner = membershipRole === 'owner';
  useEffect(() => { if (owner && !inviteLoaded) void loadInvite(); }, [owner, inviteLoaded]);
  return <div className="screen settings-screen settings-detail-screen"><header className="topbar"><button className="back-btn" aria-label="Вернуться к настройкам" type="button" onClick={onBack}>← Назад</button><div><p className="eyebrow">Настройки</p><h2>Семья</h2></div></header>
    <section className="card family-section"><div className="section-title"><div><p className="eyebrow">Название семьи</p><h4>{household?.name || 'Моя семья'}</h4></div><button className="text-action" type="button" onClick={() => { setFamilyName(household?.name || ''); setEditingFamily(true); }}>Редактировать</button></div>{editingFamily ? <div className="family-name-editor"><input value={familyName} onChange={(event) => setFamilyName(event.target.value)} aria-label="Название семьи"/><button className="primary-btn" type="button" disabled={saving} onClick={saveFamily}>Сохранить</button><button className="ghost-btn" type="button" onClick={() => setEditingFamily(false)}>Отмена</button></div> : null}</section>
    <section className="card family-section"><div className="section-title"><h4>Участники</h4><button className="text-action" type="button" onClick={() => setDraft({ name: '', avatar: '🧑' })}>Добавить</button></div><div className="settings-users">{users.map((user) => <div className="settings-user" key={user.id}><span className="settings-user-avatar">{user.avatar}</span><strong>{user.name}</strong><button className="text-action" type="button" onClick={() => setDraft({ ...user })}>Изменить</button><button className="text-action danger" type="button" onClick={() => onDeleteUser(user)}>Удалить</button></div>)}{!users.length ? <p className="muted">Добавьте первого участника семьи.</p> : null}</div>{draft ? <div className="settings-user settings-user--editor"><label className="field"><span>Имя</span><input autoFocus value={draft.name} onChange={(event) => setDraft({ ...draft, name: event.target.value })}/></label><div className="avatar-picker compact">{AVATARS.map((avatar) => <button key={avatar} type="button" className={draft.avatar === avatar ? 'active' : ''} onClick={() => setDraft({ ...draft, avatar })}>{avatar}</button>)}</div><div className="settings-actions"><button className="primary-btn" type="button" disabled={saving} onClick={saveUser}>{saving ? 'Сохраняем…' : 'Сохранить'}</button><button className="ghost-btn" type="button" onClick={() => setDraft(null)}>Отмена</button></div></div> : null}</section>
    <section className="card family-section"><div className="section-title"><div><p className="eyebrow">Совместный доступ</p><h4>Аккаунты с доступом</h4></div>{owner && !inviteLoaded ? <button className="text-action" type="button" onClick={loadInvite}>Проверить</button> : null}</div><div className="access-member-list">{accessMembers.map((member) => <div className="settings-user" key={member.auth_user_id}><span className="settings-user-avatar">{member.role === 'owner' ? '👑' : '👤'}</span><strong>{member.is_current ? 'Этот аккаунт' : 'Участник семьи'}</strong><span className="access-role">{member.role === 'owner' ? 'Владелец' : 'Участник'}</span></div>)}</div>{owner ? <div className="invite-panel">{invite?.code ? <><p>Код можно использовать один раз</p><output className="invite-code">{invite.code}</output><p className="muted">Действует до {new Intl.DateTimeFormat('ru-RU', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(invite.expires_at))}</p><div className="settings-actions"><button className="primary-btn" type="button" onClick={copyInvite}>Скопировать код</button><button className="ghost-btn" type="button" disabled={inviteLoading} onClick={createInvite}>Создать новый код</button></div><button className="text-action danger" type="button" disabled={inviteLoading} onClick={async () => { await revokeHouseholdInvite(invite.invite_id); setInvite(null); onStatus('Приглашение отменено'); }}>Отменить приглашение</button></> : invite ? <><p>Активное приглашение действует до {new Intl.DateTimeFormat('ru-RU', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(invite.expires_at))}.</p><p className="muted">Полный код не хранится. Чтобы получить новый код, создайте новое приглашение.</p><button className="primary-btn" type="button" disabled={inviteLoading} onClick={createInvite}>Создать новый код</button></> : <><p className="muted">Создайте одноразовый код на 24 часа, чтобы пригласить другого человека.</p><button className="primary-btn" type="button" disabled={inviteLoading} onClick={createInvite}>{inviteLoading ? 'Создаём…' : 'Создать приглашение'}</button></>}</div> : <p className="muted">Вы являетесь участником этой семьи.</p>}</section>
  </div>;
}
export default SettingsFamilyPage;
