import { useState } from 'react';
import { AVATARS } from '../components/OnboardingWizard';

function SettingsFamilyPage({ household, users, onBack, onUpdateHouseholdName, onCreateUser, onUpdateUser, onDeleteUser, onStatus }) {
  const [editingFamily, setEditingFamily] = useState(false);
  const [familyName, setFamilyName] = useState(household?.name || '');
  const [draft, setDraft] = useState(null);
  const [saving, setSaving] = useState(false);
  const saveFamily = async () => { if (!familyName.trim()) return; setSaving(true); try { await onUpdateHouseholdName(familyName.trim()); setEditingFamily(false); onStatus('Название семьи сохранено'); } catch { onStatus('Не удалось сохранить название семьи'); } finally { setSaving(false); } };
  const saveUser = async () => { if (!draft?.name?.trim()) return; setSaving(true); try { if (draft.id) await onUpdateUser(draft.id, draft); else await onCreateUser(draft); setDraft(null); onStatus('Участник сохранён'); } catch { onStatus('Не удалось сохранить участника'); } finally { setSaving(false); } };
  return <div className="screen settings-screen settings-detail-screen"><header className="topbar"><button className="back-btn" aria-label="Вернуться к настройкам" type="button" onClick={onBack}>← Назад</button><div><p className="eyebrow">Настройки</p><h2>Семья</h2></div></header>
    <section className="card family-section"><div className="section-title"><div><p className="eyebrow">Название семьи</p><h4>{household?.name || 'Моя семья'}</h4></div><button className="text-action" type="button" onClick={() => { setFamilyName(household?.name || ''); setEditingFamily(true); }}>Редактировать</button></div>{editingFamily ? <div className="family-name-editor"><input value={familyName} onChange={(event) => setFamilyName(event.target.value)} aria-label="Название семьи"/><button className="primary-btn" type="button" disabled={saving} onClick={saveFamily}>Сохранить</button><button className="ghost-btn" type="button" onClick={() => setEditingFamily(false)}>Отмена</button></div> : null}</section>
    <section className="card family-section"><div className="section-title"><h4>Участники</h4><button className="text-action" type="button" onClick={() => setDraft({ name: '', avatar: '🧑' })}>Добавить</button></div><div className="settings-users">{users.map((user) => <div className="settings-user" key={user.id}><span className="settings-user-avatar">{user.avatar}</span><strong>{user.name}</strong><button className="text-action" type="button" onClick={() => setDraft({ ...user })}>Изменить</button><button className="text-action danger" type="button" onClick={() => onDeleteUser(user)}>Удалить</button></div>)}{!users.length ? <p className="muted">Добавьте первого участника семьи.</p> : null}</div>{draft ? <div className="settings-user settings-user--editor"><label className="field"><span>Имя</span><input autoFocus value={draft.name} onChange={(event) => setDraft({ ...draft, name: event.target.value })}/></label><div className="avatar-picker compact">{AVATARS.map((avatar) => <button key={avatar} type="button" className={draft.avatar === avatar ? 'active' : ''} onClick={() => setDraft({ ...draft, avatar })}>{avatar}</button>)}</div><div className="settings-actions"><button className="primary-btn" type="button" disabled={saving} onClick={saveUser}>{saving ? 'Сохраняем…' : 'Сохранить'}</button><button className="ghost-btn" type="button" onClick={() => setDraft(null)}>Отмена</button></div></div> : null}</section>
  </div>;
}
export default SettingsFamilyPage;
