import { useState } from 'react';
import { DEFAULT_USERS } from '../utils/settingsStorage';
import { createDefaultCategories } from '../utils/categoryStorage';

export const AVATARS = ['👨','👩','🧑','👱‍♂️','👱‍♀️','🐶','🐱','🐻','🦊','🐼','🐸','🦁'];

function OnboardingWizard({ onComplete }) {
  const [step, setStep] = useState(1); const [currency, setCurrency] = useState('EUR'); const [balance, setBalance] = useState('');
  const [firstUser, setFirstUser] = useState(() => ({ ...DEFAULT_USERS[0], name: '', previousNames: [], legacyNames: [] })); const [addSecond, setAddSecond] = useState(false); const [secondUser, setSecondUser] = useState(() => ({ ...DEFAULT_USERS[1], name: '', previousNames: [], legacyNames: [] }));
  const [categories, setCategories] = useState(() => createDefaultCategories().map((category) => ({ ...category, archived: true }))); const [custom, setCustom] = useState('');
  const users = [firstUser, ...(addSecond ? [secondUser] : [])].map((user) => ({ ...user, legacyNames: [user.name], previousNames: [user.name], archived: false }));
  const categoryStep = (type, title) => <div className="onboarding-step"><h2>{title}</h2><div className="category-grid">{categories.filter((item) => item.type === type).map((item) => <button key={item.id} type="button" className={`category-btn ${item.archived ? '' : 'active'}`} onClick={() => setCategories(categories.map((category) => category.id === item.id ? { ...category, archived: !category.archived } : category))}><span>{item.icon}</span><strong>{item.name}</strong></button>)}</div><div className="onboarding-custom-category"><input value={custom} onChange={(event) => setCustom(event.target.value)} placeholder="Своя категория" /><button className="ghost-btn" type="button" onClick={() => { const name = custom.trim(); if (!name) return; setCategories([...categories, { id: `category-${Date.now()}`, name, label: name, icon: '📦', type, archived: false, previousNames: [name], createdAt: new Date().toISOString() }]); setCustom(''); }}>Добавить</button></div></div>;
  const userEditor = (user, setUser, title) => <div className="onboarding-step"><h2>{title}</h2><input value={user.name} onChange={(event) => setUser({ ...user, name: event.target.value })} placeholder="Введите имя" /><div className="avatar-picker">{AVATARS.map((avatar) => <button key={avatar} type="button" className={user.avatar === avatar ? 'active' : ''} onClick={() => setUser({ ...user, avatar })}>{avatar}</button>)}</div></div>;
  const canContinue = !((step === 3 && !firstUser.name.trim()) || (step === 5 && !categories.some((item) => item.type === 'expense' && !item.archived)) || (step === 6 && !categories.some((item) => item.type === 'income' && !item.archived)));
  return <div className="onboarding-shell"><div className="card onboarding-card"><p className="eyebrow">Настройка {step} из 7</p>{step === 1 && <div className="onboarding-step"><h2>Выберите валюту</h2><div className="choice-grid">{['EUR','USD','RUB','PLN','UAH'].map((item) => <button key={item} type="button" className={currency === item ? 'active' : ''} onClick={() => setCurrency(item)}>{item}</button>)}</div></div>}{step === 2 && <div className="onboarding-step"><h2>Начальный баланс</h2><input type="number" value={balance} onChange={(event) => setBalance(event.target.value)} placeholder="0,00" /></div>}{step === 3 && userEditor(firstUser, setFirstUser, 'Первый пользователь')}{step === 4 && <div className="onboarding-step"><h2>Добавить второго?</h2><label className="onboarding-check"><input type="checkbox" checked={addSecond} onChange={(event) => setAddSecond(event.target.checked)} /> Добавить ещё пользователя</label>{addSecond && userEditor(secondUser, setSecondUser, 'Второй пользователь')}</div>}{step === 5 && categoryStep('expense', 'Выберите категории расходов')}{step === 6 && categoryStep('income', 'Выберите категории доходов')}{step === 7 && <div className="onboarding-step"><h2>Всё готово</h2><p>Категории можно изменить позже в настройках.</p></div>}<div className="onboarding-actions">{step > 1 && <button className="ghost-btn" type="button" onClick={() => setStep(step - 1)}>Назад</button>}{step < 7 ? <button className="primary-btn" type="button" disabled={!canContinue} onClick={() => setStep(step + 1)}>Продолжить</button> : <button className="primary-btn" type="button" onClick={() => onComplete({ baseCurrency: currency, currency, balance: Number(String(balance).replace(',', '.')) || 0, users, categories: categories.filter((item) => !item.archived) })}>Начать</button>}</div></div></div>;
}
export default OnboardingWizard;
